name: Update Portfolio Site

on:
  push:
    branches:
      - main  # Trigger on updates to the main branch; adjust if needed
  release:
    types: [published]  # Trigger on release publication

jobs:
  update-portfolio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Clone Portfolio Repo
        run: |
          git clone https://peterbenoit:${{ secrets.PAT_FOR_PORTFOLIO_REPO }}@github.com/peterbenoit/peterbenoit.github.io portfolio
          cd portfolio
          git config user.name "peterbenoit"
          git config user.email "peterbenoit@gmail.com"

      - name: Copy Updated Library
        run: cp ./resourceLoader.js ./portfolio/libraries/resourceLoader.js

      - name: Commit and Push Changes
        run: |
          cd portfolio
          git add .
          git commit -m "Update ResourceLoader in portfolio"
          git push https://peterbenoit:${{ secrets.PAT_FOR_PORTFOLIO_REPO }}@github.com/peterbenoit/peterbenoit.github.io
